ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
DOCKER_HOST_NAME = "vagrant-dockerhost"
DOCKER_HOST_VAGRANTFILE = "../Vagrantfile"

# A little example / test docker container
# That will be running under docker in turn running under vagrant-dockerhost VM
# Kicks up a bash shell
# Access by "vagrant ssh" from vagrantShare, then "docker attach" the container within

Vagrant.configure("2") do |config|

  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end 

  config.vm.synced_folder "../.", "/vagrantShare"
  config.vm.boot_timeout = 300
  config.vm.box_check_update = false
  config.vm.define "myService" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "."
      d.build_args = ["-t=phusion"] # labels must be all lowercase
      d.name = "Phusion"
      d.remains_running = true  
      d.vagrant_machine = "#{DOCKER_HOST_NAME}"
      d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
      d.cmd = ["/bin/bash"]
      d.create_args = ["-t", "-i"]
      # Specify port mappings
      # If omitted, no ports are mapped!
      # E.g. d.ports = ['8080:80', '4443:443']
      # No ports for this little test container - only bash running
    end
  end

end
