ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
DOCKER_HOST_NAME = "dockerhost"
DOCKER_HOST_VAGRANTFILE = "./DockerHostVagrantfile"
 
Vagrant.configure("2") do |config|
 
  config.vm.synced_folder "./.", "/vagrantShare"
  config.vm.define "myService" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "."
      d.build_args = ["-t=ubuntu"] # labels must be all lowercase
      d.name = "Ubuntu"
      d.remains_running = true
      d.vagrant_machine = "#{DOCKER_HOST_NAME}"
      d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
      d.cmd = ["/bin/bash"]
      d.create_args = ["-t", "-i"]
    end
  end

end
